### ISSUE TITLE
PNG not rendering on Mac

### ISSUE THREAD

**Issue by aok2715** [yakovmeister/pdf2image#1]
Hello.  I have been using your pdf2pic library on a mac.  I very much like the package.  It is working as expected on one mac.  However, on another, the same code produces some weirdness.  Instead of rendering a PNG (as it does on the first mac), it renders a PDF.  So it appears to be taking each page of the pdf and making a single-paged pdf document for it.

Was wondering if you have seen this and if there is perhaps a configuration issue that I am overlooking?  I have gm and gs both installed on the macs.

**Comment by yakovmeister** [comment]
Thank you for reaching out, this behavior seems new to me, in order for me to take a look further can you please provide the following if possible?

- installed graphicsmagick version
- mac OS version
- installed pdf2pic version
- screenshot of your code where issue occurred 
- screenshot of the output
- error message if there's any

I'll take a look into this issue again once the following things are provided. Thanks.
