### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: write EPIPE

### ISSUE THREAD

**Issue by jayaruvan** [yakovmeister/pdf2image#106]
Given example is not working.  
Please see the code

`
const fromPath = require("pdf2pic").fromPath;

const options = {
    density: 100,
    saveFilename: "untitled",
    savePath: "./images",
    format: "png",
    width: 600,
    height: 600
};
const storeAsImage = fromPath("./images/sample.pdf", options);
const pageToConvertAsImage = 1;

storeAsImage(pageToConvertAsImage).then((resolve) => {
    console.log("Page 1 is now converted as image");

    return resolve;
});
`

This results in an error

`
(node:20252) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at ReadStream.ondata (internal/streams/readable.js:719:22)
    at ReadStream.emit (events.js:315:20)
    at ReadStream.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

How can I resolve this?

**Comment by vnt32** [comment]
Такая же ошибка!

**Comment by jayaruvan** [comment]
you mean,
is this a known mistake?

**Comment by trottdeaje** [comment]
I'm having this issue also.

**Comment by jayaruvan** [comment]
bump

**Comment by jayaruvan** [comment]
For Some reason below worked for me. 

`
const fromBase64 = require("pdf2pic").fromBase64;


						const options = {
							density: 96,
							saveFilename: save_file_name,
							savePath: savePath,
							format: "jpg",
							width: 1654,
							height: 2339
						};

						const buffer = fs.readFileSync(res.full_pdf_file_name, {
							encoding: 'base64'
						});
						const storeAsImage = fromBase64(buffer, options);
						storeAsImage(1).then(async (resolve) => {
							console.log(' saveAs image ==>', resolve);
							console.log("Page 1 is now converted as image");
							if (resolve) {

								await UserPdfSchema.findOneAndUpdate({
									_id: req.params.id
								}, {
									pdf2jpgName: resolve.name,
									pdffilename: filename,
									isUploaded: true,
									pdf2jpg: true,
									isActive: true
								});

							}
						});
`

**Comment by FelipeDeveloperFullStack** [comment]
> For Some reason below worked for me.
> 
> `
> const fromBase64 = require("pdf2pic").fromBase64;
> 
> ```
> 					const options = {
> 						density: 96,
> 						saveFilename: save_file_name,
> 						savePath: savePath,
> 						format: "jpg",
> 						width: 1654,
> 						height: 2339
> 					};
> 
> 					const buffer = fs.readFileSync(res.full_pdf_file_name, {
> 						encoding: 'base64'
> 					});
> 					const storeAsImage = fromBase64(buffer, options);
> 					storeAsImage(1).then(async (resolve) => {
> 						console.log(' saveAs image ==>', resolve);
> 						console.log("Page 1 is now converted as image");
> 						if (resolve) {
> 
> 							await UserPdfSchema.findOneAndUpdate({
> 								_id: req.params.id
> 							}, {
> 								pdf2jpgName: resolve.name,
> 								pdffilename: filename,
> 								isUploaded: true,
> 								pdf2jpg: true,
> 								isActive: true
> 							});
> 
> 						}
> 					});
> ```
> 
> `

Is not working for me 👎

**Comment by jayaruvan** [comment]
bump!

**Comment by Duegreg** [comment]
I'm having the same issue also. Could not make it run, while other npm packages with the same dependencies are fine.

**Comment by jayaruvan** [comment]
Yes, I was able to do the same. using an older version of gm solved it

**Comment by satoshibles** [comment]
What version of GM?

**Comment by jayaruvan** [comment]
"gm": "^1.23.1",
"pdf2pic": "^2.1.4",
(Check with above )
