### ISSUE TITLE
improve `Convert` returned types

### ISSUE THREAD

**Issue by getlarge** [yakovmeister/pdf2image#134]
Hey thanks for the nice lib.

When using the converter methods i need to cast manually the returned type which could be avoided by doing something like this :

```ts
export type Convert = {

  bulk?: (pages?: number | number[], toBase64?: boolean) => Promise<WriteImageResponse[] | ToBase64Response[]>;

  setOptions?: () => void;

  setGMClass?: (gmClass: string | boolean) => void;

  <B extends boolean = false>(page?: number, toBase64?: B):  B extends true ? Promise<ToBase64Response> : Promise<WriteImageResponse>;
}
```

@yakovmeister  I would be willing to create a PR if you like the idea.

**Comment by nidhil931** [comment]
Thanks for this. I will need this so I will create a PR for now and use it for my project. Hopefully, it gets merged soon

**Comment by pjerryhu** [comment]
For people who are blocked by this same problem. This worked for me:

```
const pdf2picConvert = pdf2pic.fromBuffer(fileBuffer, {
    format: 'png',
    preserveAspectRatio: true,
    density: dpi // output pixels per inch
  })
  pdf2picConvert.setGMClass(true) // Use ImageMagick - this is the key line, so you don't have to touch return type

  const pageNumber = 1
  const imageBufferResponse = await pdf2picConvert(pageNumber, {
    responseType: 'buffer'
  })
```

**Comment by mskec** [comment]
Hi, we added return types a couple of months ago. 
If they are still a problem please reopen the issue with description and code snippet that is not working.
