### ISSUE TITLE
Node Module issues

### ISSUE THREAD

**Issue by adnanrafique** [yakovmeister/pdf2image#153]
I have installed this in my Angular 11 Application, I get no errors while importing fromPath but as soon as I try to use fromPath it gives me error shown in the screenshot.

I am using macOs Monterey and have installed the ghostscript and graphicsmagick in my laptop using homebrew. My node version is v16.14.2. 

There was no mention of importing anything in angular.json from node_modules etc, should I import something in the node_modules?

Please help me to understand what I am missing

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/20041254/165052538-976dcc52-e813-474e-b409-c069b1ffda86.png">

**Comment by kippenator** [comment]
This package works in node.js, not in your browser.
fs and path are node api's, browsers don't have them.

**Comment by adnanrafique** [comment]
So I cannot use this package in Angular Application?

**Comment by mskec** [comment]
The package only supports node.js environment as stated in [prerequisites](https://github.com/yakovmeister/pdf2image#prerequisite). 
It cannot work in the browser and probably not in the mobile app.
