### ISSUE TITLE
.setGMClass(true).bulk(-1, false)

### ISSUE THREAD

**Issue by dev-fredericfox** [yakovmeister/pdf2image#155]
I am using following:
` await fromPath(
        pathForThePDFThatWeWantToTest,
        options
      ).setGMClass(true).bulk(-1, false)` but I am getting this error ` TypeError: Cannot read properties of undefined (reading 'bulk')`. It works fine when I omit `.setGMClass(true)`. Anyone knows why?

**Comment by hongphuc5497** [comment]
You should define `setGMK` before calling `bulk`, for example

```		
const storeAsImage = fromPath( pathForThePDFThatWeWantToTest, options ).setGMClass(true)
const images = await storeAsImage.bulk(-1, false);
```
