### ISSUE TITLE
Can not use fromPath with an absolute url

### ISSUE THREAD

**Issue by enoh-barbu** [yakovmeister/pdf2image#156]
I was trying to load the pdf by using an absolute URL, but it looks like it gets concatenated with the directory's URL

eg 

`fromPath('https://www.site.com/test.pdf')` ends up with an error 

`[Error: ENOENT: no such file or directory, open 'D:\project\https://www.site.com/test.pdf']`

**Comment by enoh-barbu** [comment]
Actually this might be correct, what I expected was to be able also to use an absolute path, but that might translate to extend the api with a new method, fromURL

**Comment by ADTC** [comment]
I wrote a utility method, but this is **untested**. (Unfortunately I cannot use this library as I [discovered](https://github.com/yakovmeister/pdf2image/issues/153), it doesn't work in a web browser. So I can't test this right now. YMMV)

```ts
import { fromBuffer } from 'pdf2pic'

import type { Options } from 'pdf2pic/dist/types/options'

export async function fromUrl(pdfUrl: string, options?: Options) {
  const response = await fetch(pdfUrl)
  if (!response.ok) {
    throw new Error(`Failed to fetch PDF: ${response.statusText}`)
  }
  const arrayBuffer = await response.arrayBuffer()
  const buffer = Buffer.from(arrayBuffer)
  return fromBuffer(buffer, options)
}
```
You can use it like so, inside an `async` function:
```
const convert = await fromUrl(myPdfUrl) // include options if necessary
```
The `convert` object will be the same one you get from the `fromBuffer` function.
