### ISSUE TITLE
Blob as input?

### ISSUE THREAD

**Issue by donniekerr** [yakovmeister/pdf2image#16]
Will this work with a PDF in blob/buffer format as input?

**Comment by yakovmeister** [comment]
As of now, Blob/Buffer as input is not yet supported. But, next release might support this feature.

**Comment by donniekerr** [comment]
Excellent! Thanks. For now I just save blob to temp file and delete it after.

**Comment by yakovmeister** [comment]
@Puyush6889 still doesn't have free time to do this, but I might just be able to add  this feature on holidays.

**Comment by susannaHayrapetyan** [comment]
@yakovmeister any update?
