### ISSUE TITLE
More info about params

### ISSUE THREAD

**Issue by hilmanski** [yakovmeister/pdf2image#160]
Hi
anyone have more information about these three options:
quality, density as well as compression

What's the value range and how we should use it (not how to code, but in general)

Thanks

**Comment by Zirafnik** [comment]
The density doesn't seem to do anything...

**Comment by mskec** [comment]
Hi @hilmanski

pdf2pic is using GraphicsMagick and passing those params. You can find more info about those params in their docs:

- [density](http://www.graphicsmagick.org/GraphicsMagick.html#details-density)
- [quality](http://www.graphicsmagick.org/GraphicsMagick.html#details-quality)
- [compression](http://www.graphicsmagick.org/GraphicsMagick.html#details-compression)

I will add those links to the README.
