### ISSUE TITLE
bulk in version 2.2.0

### ISSUE THREAD

**Issue by ezek835** [yakovmeister/pdf2image#166]
It tells me that "bulk" does not exist when I update the library to the latest version. My question is how can I use it or how can I generate all the pages of the pdf

**Comment by mskec** [comment]
Hi @ezek835, can you provide the code snippet and node.js version you are using?

Generally, you can use bulk like this `fromPath(filePath, options).bulk(pageNumber, isBase64)`.

**Comment by alvIndieDevelop** [comment]
Hi, i use bulk like this in typeScript.
`const convert: Convert = fromBase64(toBase64, {
      density: 300,
      format: "png",
    });
    const finish: any = await convert.bulk?.(-1, true);`
