### ISSUE TITLE
Breaking Types

### ISSUE THREAD

**Issue by piyushk96** [yakovmeister/pdf2image#181]
In latest version 3.0.1 the types folder is missing which is breaking all the types. 
<img width="357" alt="image" src="https://github.com/yakovmeister/pdf2image/assets/41179062/19880a15-68d7-49e5-9cff-870d5195a6d4">
<img width="1059" alt="image" src="https://github.com/yakovmeister/pdf2image/assets/41179062/df305042-b098-4e78-a1b0-384ae56b8a46">

**Comment by yakovmeister** [comment]
Hi @piyushk96, thank you for reporting this issue, this is now corrected in the latest build.
