### ISSUE TITLE
Unable to create image buffer from pdf buffer

### ISSUE THREAD

**Issue by prafulkadam007** [yakovmeister/pdf2image#190]
const { fromBuffer } = require("pdf2pic");

let fileBuffer = fs.readFileSync(__dirname + "/test.pdf");

const options = {
  format: "png"
};

const pdfConvert = fromBuffer(fileBuffer, options)

const bufferResponse = await pdfConvert(1, { responseType: 'buffer' });
fileBuffer = bufferResponse.buffer
console.log(`fileBuffer ${bufferResponse.buffer}`)

Above prints empty fileBuffer value. Am I missing something here?
Thanks in advance

**Comment by prafulkadam007** [comment]
Closing this issue as it was due to missing graphicsmagick lib

**Comment by brianMxBm** [comment]
Seem to be getting a similar issue. I'm applying the dependencies of ghost-script and graphicsmagick via lambda layers though. Consistently getting an empty buffer.

**Comment by vhlima** [comment]
Hey @brianMxBm, I'm encountering the same problem. When running locally, everything works fine, but on Lambda with dependencies in layers, I'm getting an empty buffer. Any insights or solutions you found? Thanks!

**Comment by mskec** [comment]
Hi, can you create and share the lambda setup that I can use for debugging?

**Comment by vhlima** [comment]
Hey @mskec, thanks for your response! Currently, I'm utilizing two layers to set up Ghostscript and GraphicsMagick for my Lambda function. You can easily add these layers using their ARNs:

```
arn:aws:lambda:us-east-1:764866452798:layer:ghostscript:15
arn:aws:lambda:us-east-1:175033217214:layer:graphicsmagick:2
```

In my scenario, I retrieve the PDF file from an S3 bucket. You can either follow the same approach or manually upload a PDF to your Lambda. Here's a snippet of how I handle the file and convert it:
```
const file = await client.send(
  new GetObjectCommand({
    Bucket: bucketName,
    Key: fileName,
  })
);

const buffer = (await file.Body.transformToByteArray()) as any;

const bufferResponse = await fromBuffer(buffer, {
  density: 100,
  quality: 100,
  format: "png"
}).bulk([1, 2], {
  responseType: "buffer",
});
```

**Comment by mskec** [comment]
Hey @vhlima, thanks for the update. 
I tried it myself by adding the latest community driven layers from your comment and it seems to be working for me. Even without using the latest gm.
