### ISSUE TITLE
Convert all pages error

### ISSUE THREAD

**Issue by brennanbatalla** [yakovmeister/pdf2image#203]
In the documentation it says you can put a -1 value for the `pages` parameter and it will convert all pages of the document. However, you actually get the following error:

`Error: Page number should be more than or equal 1`

**Comment by Gamurar** [comment]
Hey, @brennanbatalla! How did you fix it?

**Comment by faileon** [comment]
> Hey, [@brennanbatalla](https://github.com/brennanbatalla)! How did you fix it?

Use the `bulk()` function

```ts
        const output = await fromPath('./sample.pdf').bulk(-1);
```
