### ISSUE TITLE
Error Using with Firebase Cloud Functions

### ISSUE THREAD

**Issue by SandMoshi** [yakovmeister/pdf2image#21]
I get an error that begins with `Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%p"` when attemping to run pdf2pic on a firebase cloud function.

I installed graphicsmagick using `npm install gm` and also installed imagemagick and then installed pdf2pic.

Versions:
`"imagemagick": "^0.1.3",`
`"gm": "^1.23.1",`
`"pdf2pic": "^1.2.6",`

Code:

I import the package 
`const PDF2Pic = require('pdf2pic').default;`

and I'm doing a bulk conversion
```
let converter = new PDF2Pic({
            density: 150,           // output pixels per inch
            savename: savename,   // output file name
            savedir: outputDirectory,    // output file location
            format: 'jpg',          // output file format
            size: 3000,               // output size in pixels
        })
```

```
 var reply = converter.convertBulk(pdfPath, [13,14,15])
            .then( () => {
                console.log('image converted successfully');
        });
```

**Comment by yakovmeister** [comment]
Have you made sure that the graphicsmagick library is pre-installed in your firebase cloud function?
