### ISSUE TITLE
require.js:5 Uncaught Error: Module name "pdf2pic" has not been loaded yet for context: _. 

### ISSUE THREAD

**Issue by harshwardhansharma1** [yakovmeister/pdf2image#22]
HI I am trying to use this mdoule . I am trying to run the module in a simple html file . 
I am getting this  Error:
require.js:5 Uncaught Error: Module name "pdf2pic" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:5)
    at Object.o [as require] (require.js:5)
    at requirejs (require.js:5)
    at functionconverter (index.html:7)
    at HTMLInputElement.onclick (index.html:20)
Please help !

[code.txt](https://github.com/yakovmeister/pdf2image/files/2802668/code.txt)

**Comment by harshwardhansharma1** [comment]
[code.txt](https://github.com/yakovmeister/pdf2image/files/2802666/code.txt)

**Comment by yakovmeister** [comment]
this library is not intended for front end use as it requires graphicsmagick binaries installed. for more information please check: http://www.graphicsmagick.org/README.html
