### ISSUE TITLE
gm convert: abort due to signal 7 (SIGBUS) "Bus Error

### ISSUE THREAD

**Issue by jaykumarthaker** [yakovmeister/pdf2image#26]
module is working fine on windows, but when deployed to EC2 (ubuntu-bionic-18.04-amd64-server-20180912) it throws:
**Error: Command failed: gm convert: abort due to signal 7 (SIGBUS) "Bus Error"...**

![screen shot 2019-02-11 at 4 25 12 pm](https://user-images.githubusercontent.com/28264318/52594505-ac393080-2e19-11e9-967f-077bfcc79802.png)

I have installed gm through:
```
sudo apt-get install graphicsmagick
```

and to confirm, I ran gm command manually and it worked:
```
gm convert pdfname.pdf imagename.png
```

so, is this something with plugin?

**Comment by yakovmeister** [comment]
@jaykumarthaker hi, can you provide some steps on how to reproduce this error? also it would be helpful if you can provide the pdf that you are using to reproduce this error. Thanks.

**Comment by jaykumarthaker** [comment]
Hey @yakovmeister, thank you so much for your quick response. I think it was the issue with installing graphicsmagick.. not a linux guys but just **_"sudo apt-get install graphicsmagick"_** doesn't seems to work as it should.. hence after a bit of research I found below script which seems to work correctly:

```sh
wget ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/1.3/GraphicsMagick-1.3.19.tar.gz
 
sudo apt-get install libgs-dev

sudo apt-get install libpng-dev

tar -xvf GraphicsMagick-1.3.19.tar.gz
 
cd GraphicsMagick-1.3.19
 
./configure --with-gslib=yes --with-png=yes
 
make
 
sudo make install
```
after this, we do not have any **Bus Error**, but the Images created with conversion are in corrupted format. You can try with [this pdf](https://github.com/yakovmeister/pdf2image/files/2856314/auto_1549918616671_7516e83e-4127-497c-b009-f9eb497ba1cf_MilanMadhavjireport.pdf) (or any other would result the in same), and the code is like:

```
const PDF2Pic = require('pdf2pic');
const delete_files_helper = require("../helpers/delete_files");

async function Convert(pdf_path, image_type, savename, doDeletePDFAfterConversion)
{
    return new Promise((resolve, reject) => {
        try
        {
            let converter = new PDF2Pic({
                density: 1000,           // output pixels per inch
                savename: savename,   // output file name
                savedir: "./temp",    // output file location
                format: image_type,          // output file format
                size: 2000               // output size in pixels
            });
        
            converter.convertBulk(pdf_path, -1).then(async _images => {
                console.log("image converted successfully");
                if(doDeletePDFAfterConversion)
                {
                    let _files_to_delete = [];
                    _files_to_delete.push(pdf_path);

                    await delete_files_helper.DeleteFiles(_files_to_delete);
                }

                resolve(_images);
            });
        }
        catch(err)
        {
            reject(err);
        }
    });
}

module.exports = Convert;
```

**Comment by yakovmeister** [comment]
I'm guessing the density is way beyond the limits of graphicsmagick. That, I cannot control. Sorry.
