### ISSUE TITLE
File stream option

### ISSUE THREAD

**Issue by DivekJohns** [yakovmeister/pdf2image#36]
Hi all,

Now, this lib returns an image location after conversion. Can we have the converted image file stream or buffer, please

as I am uploading the image to cloud an extra delete operation is needed now which is making one of API bit slower

**Comment by yakovmeister** [comment]
Hi,

As of now, there's no option for you to have a Stream or Buffer as response. However, the lib already supports base64 as response. The snippet below is an example on how to convert pdf to base64 image. Please let me know if it still is not enough. Thanks.

``javascript
const PDF2Pic = require("pdf2pic");

const pdf2pic = new PDF2Pic({
  density: 100,           // output pixels per inch
  savename: "untitled",   // output file name
  savedir: "./images",    // output file location
  format: "png",          // output file format
  size: "600x600"         // output size in pixels
});

pdf2pic.convertToBase64("path/to/pdf/sample.pdf").then((resolve) => {
  if (resolve.base64) {
    console.log("image converter successfully!");

    // assuming you're using some ORM to save base64 to db
    return db.model.table('users').update({id: "1", image: resolve.base64});
  }
});
```

**Comment by DivekJohns** [comment]
Thank you I have made some changes that can work as required, the problem
is aws cloud storage needs a stream while upload because the pdf2image lib
stores images in a folder, which was not required for me. However I have
directly made readstream using the file location and then upload it.


Thank you pro great library, very helpful to me,
