### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by JoffreyFrancesch** [yakovmeister/pdf2image#4]
Hi, 
I have a problem when i running your module and I don't understand why.
<img width="1018" alt="capture d ecran 2018-01-26 a 09 02 41" src="https://user-images.githubusercontent.com/23345918/35430247-b86dc7a4-0277-11e8-9333-a8fd15413d22.png">

I'm on Mac OS HighSierra and NodeJS 9.2.0
Can you help me ?

**Comment by yakovmeister** [comment]
Hi there, thanks for your feedback, may I ask what version of pdf2pic are have you installed? Also, are you trying to run the module as CLI?

**Comment by JoffreyFrancesch** [comment]
I use the 1.1.6 version. And i haven't try to run the module as CLI. 
There is a sample of my code : 
<img width="778" alt="capture d ecran 2018-01-26 a 09 51 28" src="https://user-images.githubusercontent.com/23345918/35431871-8ac398fe-027e-11e8-9539-6ab5f7307677.png">

**Comment by yakovmeister** [comment]
Can you please provide a screenshot of file/directory hierarchy from node_modules/pdf2pic?

**Comment by JoffreyFrancesch** [comment]
<img width="284" alt="capture d ecran 2018-01-26 a 10 32 40" src="https://user-images.githubusercontent.com/23345918/35433592-52e70852-0284-11e8-98d6-aba33479fba4.png">

**Comment by yakovmeister** [comment]
thanks, now can you check if there's an existing index.php inside node_modules/pdf2pic/lib? if none, please try to reinstall the module. I'll take a look at this later on mac. thanks again

**Comment by yakovmeister** [comment]
update: I've run a CI for high sierra build, and it did run just fine. Please try to reinstall the module and check if it works.

**Comment by JoffreyFrancesch** [comment]
Yes, i have reinstall the module and there is no error anymore, thx ;)
