### ISSUE TITLE
All pages are not being converted

### ISSUE THREAD

**Issue by nomercy0** [yakovmeister/pdf2image#45]
All pages are not being converted . Some pages are being skipped  from the beggining .
It is generating a lot of inconsistency

I am using` pdf2pic.convertBulk(pdfPath, -1)`

Please find pdf attached 
[temp-DTH-0ZZh9TGv7GDCjlUH4Q-3216.pdf](https://github.com/yakovmeister/pdf2image/files/3959469/temp-DTH-0ZZh9TGv7GDCjlUH4Q-3216.pdf)
[temp-xGC5a_ezqt09pgjPf_f5UA-3051.pdf](https://github.com/yakovmeister/pdf2image/files/3959546/temp-xGC5a_ezqt09pgjPf_f5UA-3051.pdf)

**Comment by Jim-IndRez** [comment]
I am seeing this behavior as well.

Based on my testing, it appears to be fine on pdf files < 10 pages long, but on longer files it starts dropping pages.

**Comment by Clauzzz** [comment]
Hey ! I found the fix. I tried making a branch and pushing it myself but it didn't allow me to push.
Anyways, in the function identify, where you do 
`return resolve(data.replace(/^[\w\W]+?1/, "1"))`
if you replace "+" with "*" it should fix it. Like so:
`return resolve(data.replace(/^[\w\W]*?1/, "1"))`

**Comment by yakovmeister** [comment]
Hi @Clauzzz , thanks mate. I'll publish some changes within the week.

**Comment by yakovmeister** [comment]
@Clauzzz alternatively you can try forking the repo and creating a pull request towards 1.0 branch.

**Comment by yakovmeister** [comment]
merged pull request: 3f15944a41e79e084a152bffb59131a29fe1ddb5

**Comment by yakovmeister** [comment]
published new version, closing this now.
