### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by akume** [yakovmeister/pdf2image#54]
Is there a best practice when trying to convert a pdf file with a lot of pages (~500 pages)?  "convertBulk" is creating a separate promise for each of the pages which is attempts to instantiate 500 gm instances.  This quickly drains the memory and shoots the CPU use up.  I've tried to submit a job in 10 page chucks but when I look at the activity monitor, the gm instances are still accumulating.

**Comment by yakovmeister** [comment]
I'll soon add a feature where you would be able to set how many maximum concurrent instance can be made.

**Comment by Sandip75** [comment]
@yakovmeister @akume   Can you tell How to handle from memory leak problem?

**Comment by savgiannis** [comment]
I also have this issue. One solution is to bulk() in batches of 10. But how can I know the page count of the pdf to setup the loop?

**Comment by mickaelmesdocteurs** [comment]
I'm having the same problem and node tells me `MaxListenersExceededWarning: Possible EventEmitter memory leak detected.`
I would love to be able to configure a bulk batch size

**Comment by irgipaulius** [comment]
me too. I'll resort to manually chunking the bulk requests

**Comment by KaKi87** [comment]
> I'll soon add a feature where you would be able to set how many maximum concurrent instance can be made.

Hello @yakovmeister, any news on this ?

For now I'm forced use the following workaround :
```js
while(true){
    const { base64 } = await convert(page++, true);
    if(base64 === 'ClJlcXVlc3RlZCBGaXJzdFBhZ2UgaXMgZ3JlYXRlciB0aGFuIHRoZSBudW1iZXIgb2YgcGFnZXMgaW4gdGhlIGZpbGU6IDExCiAgIE5vIHBhZ2VzIHdpbGwgYmUgcHJvY2Vzc2VkIChGaXJzdFBhZ2UgPiBMYXN0UGFnZSkuCg==')
        break;
}
```

Thanks
