### ISSUE TITLE
Keep transparency

### ISSUE THREAD

**Issue by Minimalpris** [yakovmeister/pdf2image#55]
Hi, 

I really this project, but I can´t get transparency to work.
Are this supported or am I doing something wrong?

my code:
 const PDF2Pic = require('pdf2pic')
            const pdf2pic = new PDF2Pic({
              density: 300, 
              savename: req.file.filename + '.png',
              savedir: uploadPath, 
              format: 'png', 
              size: '600x600' 
            })
pdf2pic.convertToBase64( ....

Take care.

[5e396253becd8d3ecc1cec12.pdf](https://github.com/yakovmeister/pdf2image/files/4153373/5e396253becd8d3ecc1cec12.pdf)
(the pdf contain a write, arrow)

**Comment by yakovmeister** [comment]
I don't think it would support transparency as by default PDF has white background in it.

**Comment by irgipaulius** [comment]
@yakovmeister that is not true. running `convert sample.pdf output.png` using  generates an image with transparent background. at least on ` ImageMagick 7.1.0-22`
