### ISSUE TITLE
Getting low Image quality after conversion

### ISSUE THREAD

**Issue by Fe-Ordan** [yakovmeister/pdf2image#61]
Hi , I'm setting the pdf2pic options as follows 
```
const pdf2pic = new PDF2Pic({
  density: 600,  // output pixels per inch
  quality:100,         
  savename: "untitled",   // output file name
  savedir: "/tmp",    // output file location
                });
```
an I tried setting size to higher resolution but every time both the image quality and resolution was not good

**Comment by ilyes495** [comment]
The same here! any solution?

**Comment by LogenP** [comment]
I set the size to 2000X2000 and that fixed it for me.

`const pdf2pic = new PDF2Pic({
  density: 600,  // output pixels per inch
  quality:100,         
  savename: "untitled",   // output file name
  savedir: "/tmp",    // output file location
size:2000X2000

                });`

**Comment by hilmanski** [comment]
Hi @LogenP 
do you remember on how you get the 2000 number, any math formula relative to the original size?

**Comment by hilmanski** [comment]
For me so far, multiply the width to 1.5 getting the results I need
