### ISSUE TITLE
run sample code failed

### ISSUE THREAD

**Issue by MicalKarl** [yakovmeister/pdf2image#70]
G:\Projects\node\convert-images>node index.js
(node:7136) UnhandledPromiseRejectionWarning: Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%p" "G:\Projects\node\convert-images\files\all-algo.pdf" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (G:\Projects\node\convert-images\node_modules\gm\lib\command.js:232:12)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.cp.emit (G:\Projects\node\convert-images\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:7136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MicalKarl** [comment]
I run the basic sample code, but failed!!!

**Comment by yakovmeister** [comment]
Hi, you have to ensure that graphicsmagick is installed.
