### ISSUE TITLE
Option to convert a Buffer or Base64

### ISSUE THREAD

**Issue by qubiack** [yakovmeister/pdf2image#72]
It would be nice to create an option to pass `Buffer` or `base64` string a source instead of `file_path`. It can be useful when users create a PDF file and this file is never save on disc.

As far as I know, actually the library to convert PDF to image with `Buffer` or `base64` input doesn't exist so it will be a huge advantage.

**Comment by mateojovani** [comment]
Yes, I also came to request this. I have a use case where I use puppeteer to generate pdf as a buffer and I'd prefer to pass to pdf2pic a buffer rather than generating an actual pdf file just to comply with pdf2pic API

**Comment by qubiack** [comment]
@yakovmeister  when you plan a new release with this feature?

**Comment by yakovmeister** [comment]
@qubiack, I released new version, it's on early stage though but it's worth giving it a try.

**Comment by mateojovani** [comment]
@yakovmeister I tried bulk converting from pdf Buffer. Seems to be working great 👍
