### ISSUE TITLE
Uncaught TypeError: Cannot read property 'native' of undefined

### ISSUE THREAD

**Issue by gftrotta-moxoff** [yakovmeister/pdf2image#81]
Hi,
in the object of the message the error that I receive generated by line 126 of fs-extra library.

My node version is v12.18.4
My npm version is 6.14.6

I simply installed the library with 
```bash
npm i pdf2pic 
```
and I imported in my js file with
```javascript
import {fromBase64} from 'pdf2pic'
```

Any solutions?
Thanks in advance.

**Comment by yakovmeister** [comment]
hi @gftrotta-moxoff, can you show me your code?

**Comment by gftrotta-moxoff** [comment]
Hi,
I think that the problem is that my application is not a nodejs application but a web browser application.
I'm using react and the error is caught on the import line.

I thought the library did not need to save any data to filesystem when frombase64 component is imported. Can I do conversion from pdf in base64 to image in base64 of a specific page in RAM?

Thanks in advance.

**Comment by yakovmeister** [comment]
Hi @gftrotta-moxoff, even if it is possible to convert pdf to base64 directly, we would still hit a brick wall as this library uses graphicsmagick to convert pdfs to images, and graphicsmagick is not available if you're planning to use pdf2pic library for frontend.
