### ISSUE TITLE
Auto image proportion

### ISSUE THREAD

**Issue by ElModdy** [yakovmeister/pdf2image#88]
Hi, is there a way to let the package handle the proportion without giving to it specific width and height?
I really appreciate any kind of help.

**Comment by yakovmeister** [comment]
this is quite hard as I need to look into pdf's metadata, but I'll think about this feature.

**Comment by AnandChowdhary** [comment]
I used `pdf2json` to parse the PDF and get its width and height, and then used these values in `pdf2pic`.

This helper method returns the width and height from a PDF Buffer:

```ts
import PDFParser from "pdf2json";

const getSizeFromPdf = (buffer: Buffer) =>
  new Promise<{ width: number; height: number }>((resolve, reject) => {
    const pdfParser = new PDFParser();
    pdfParser.parseBuffer(buffer);
    pdfParser.on('pdfParser_dataError', (errData: { parserError: string }) =>
      reject(errData.parserError),
    );
    pdfParser.on('pdfParser_dataReady', (pdfData: any) => {
      if (
        typeof pdfData.formImage !== 'object' ||
        !('Pages' in pdfData.formImage) ||
        !Array.isArray(pdfData.formImage.Pages)
      )
        return reject('Unable to parse PDF');
      // Values are in "page size" not pixels, so we multiply by 25 (e.g., 38.25 becomes 957px)
      resolve({
        width: Math.round(pdfData.formImage.Width * 25),
        height: Math.round(pdfData.formImage.Pages[0].Height * 25),
      });
    });
  });
```

You can use it like so, capturing exceptions:

```ts
let width = 1000;
let height = 1400;
try {
  const size = await getSizeFromPdf(buffer);
  if (size.width) width = size.width;
  if (size.height) height = size.height;
} catch (error) {}
const image = (await fromBuffer(buffer, {
  width,
  height,
}).bulk(1);
```

**Comment by JasonLamv-t** [comment]
I found that in use, the ratio of length to width can be automatically recognized without specifying the width and height in the option, but they are transposed in the output picture.

Here is the result that I did not specify the length and width:
![image](https://user-images.githubusercontent.com/39087996/127959068-9e0f5f8c-c3c9-46c3-a69f-7cdaf3793261.png)
and the output:
```
{
  name: 'page.1.jpg',
  size: '768x512',
  fileSize: 42.859,
  path: '/tmp/images/page.1.jpg',
  page: 1
}
```

This is the result obtained by specifying a width of 512 and a height of 768:
![image](https://user-images.githubusercontent.com/39087996/127959345-438eebe9-732d-4ad4-bbd5-b5a56784f582.png)

**Comment by yusunglee2074** [comment]
@JasonLamv-t I find numbers 512, 768 on height and width.
this lib always returns 512, 768.
what ever you represent 1000 x 600 or 600 x 1000 image.

**Comment by rigwild** [comment]
You can use https://github.com/calipersjs/calipers-pdf to get the size of the document before extracting its pages:

```ts
;(async () => {
	  const Calipers = require('calipers')('pdf')
	  
	  const filePath = path.resolve(__dirname, 'lol.pdf')
	  
	  const { pages: pagesSizes } = (await Calipers.measure(filePath)) as { pages: [{ width: number; height: number }] }
	  const results: WriteImageResponse[] = []
	  
  let pageNumber = 1
	  for (const pageSize of pagesSizes) {
	    results.push((await pdf2Pic(filePath, {
	      saveFilename: `${path.basename(filePath)}`,
	      savePath: path.dirname(filePath),
	      width: pageSize.width,
	      height:pageSize.height,
	      format: 'png',
	      quality: 100,
	    }).bulk!(pageNumber))[0])
	    pageNumber++
	  }
	  return results
})()
```

To install

```sh
sudo apt install pkg-config libpoppler-cpp-dev libpoppler-private-dev
pnpm i calipers calipers-pdf
```

**Comment by KaKi87** [comment]
@yakovmeister Any news on this as well ?

PS : a PDF can have pages with different sizes.

**Comment by mskec** [comment]
You can keep the aspect ratio by setting `width` and `height` to `undefined` eg.
```js
fromPath("./mypdf.pdf", { width: undefined, height: undefined });
```

Using `density`, you can get larger/smaller image.

You can also control height and keep the aspect ratio by setting only width to `undefined` eg.
```js
fromPath("./mypdf.pdf", { width: undefined, height: 600 });
```

Hope this helps for me.

We will change defaults in the next major version and allow setting width while preserving the aspect ratio.
