### ISSUE TITLE
Not support GraphicsMagick-1.3.36

### ISSUE THREAD

**Issue by ivysrono** [yakovmeister/pdf2image#90]
Windows 10
`command.js?ee94:232 Uncaught (in promise) Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%p" "-" this most likely means the gm/convert binaries can't be found`
Update https://github.com/yakovmeister/pdf2image/blob/next/docs/gm-installation.md or support it.

**Comment by yakovmeister** [comment]
I don't think it is not supported, based on the error message, graphicsmagick binary are not found, please ensure that the gm path is added as environmental variable.

**Comment by ivysrono** [comment]
Maybe GM's bug?
![图片](https://user-images.githubusercontent.com/2649544/105579640-a0569700-5dc2-11eb-999b-7b725a431de2.png)

```
PS C:\Program Files\GraphicsMagick-1.3.35-Q16> .\gm.exe
GraphicsMagick 1.3.35 2020-02-23 Q16 http://www.GraphicsMagick.org/
Copyright (C) 2002-2020 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.
Usage: C:\Program Files\GraphicsMagick-1.3.35-Q16\gm.exe command [options ...]

Where commands include:
      batch - issue multiple commands in interactive or batch mode
  benchmark - benchmark one of the other commands
    compare - compare two images
  composite - composite images together
    conjure - execute a Magick Scripting Language (MSL) XML script
    convert - convert an image or sequence of images
       help - obtain usage message for named command
   identify - describe an image or image sequence
    mogrify - transform an image or sequence of images
    montage - create a composite image (in a grid) from separate images
       time - time one of the other commands
    version - obtain release version
   register - register this application as the source of messages
PS C:\Program Files\GraphicsMagick-1.3.35-Q16>
```

**Comment by ogimgio** [comment]
I have the same issue. I can find graphicsmagik when running it from the console, but when i run the packaged Electron app it cannot find the gm binaries anymore

**Comment by ivysrono** [comment]
xpdf works well.
