### ISSUE TITLE
Feature request: support options long and short to replace height and width

### ISSUE THREAD

**Issue by ivysrono** [yakovmeister/pdf2image#91]
For documents with mixed vertical and horizontal pages.

**Comment by yakovmeister** [comment]
I don't quite get it. Can you explain even further to make it more understandable?

**Comment by ivysrono** [comment]
Sorry for my poor english.

vertical A4： 
height: 297mm
width: 210mm

horizontal A4:
height: 210mm
width: 297mm

If I don't set options, the output images will adaptive the pages' direction, wertical or horizontal.
However, the default number is too small.
What should I do to set them?

**Comment by ivysrono** [comment]
xpdf works well.
